name: LEDAcryptKEMLT52
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 19040
length-secret-key: 42
length-ciphertext: 19040
length-shared-secret: 64
nistkat-sha256: 9cd9299d20a1c8c242730d3795683a9e87c6bcd0e691dc1fd54cd6a418266c36
principal-submitters:
  - Marco Baldi
auxiliary-submitters:
  - Alessandro Barenghi
  - Franco Chiaraluce
  - Gerardo Pelosi
  - Paolo Santini
implementations:
  - name: leaktime
    version: 2.?
